package workspace

import "errors"

var (
	ErrDocumentNotFoundOrUnauthorized = errors.New("文档不存在或无权访问")
	ErrDocumentNotFoundOrDeleted      = errors.New("文档不存在或已被删除")
	ErrInvalidShareRole               = errors.New("无效的共享角色")
	ErrCannotShareSelf                = errors.New("不能给自己共享文档")
	ErrTargetUserNotFound             = errors.New("目标用户不存在")
	ErrTargetUserEmailUnverified      = errors.New("目标用户邮箱未验证")
	ErrCollaboratorGrantRestricted    = errors.New("协同者不能授予协同者权限")
	ErrCannotRemoveSelf               = errors.New("不能移除自己")
	ErrCannotRemoveOwner              = errors.New("不能移除文档所有者")
	ErrCollaboratorRemoveRestricted   = errors.New("协同者不能移除协同者")
	ErrMemberNotFound                 = errors.New("成员不存在")
	ErrOwnerCannotLeaveShared         = errors.New("所有者不能退出自己的文档共享")
	ErrNotificationNotFound           = errors.New("通知不存在")
	ErrInviteNotFound                 = errors.New("邀请不存在")
	ErrInviteInvalidStatus            = errors.New("邀请状态无效")
	ErrInviteInvalidRole              = errors.New("邀请角色无效")
	ErrInviteEmailRequired            = errors.New("邮箱不能为空")
	ErrSharingDisabled                = errors.New("邮箱邀请功能未启用")
	ErrSharingEmailUnverified         = errors.New("邮箱未验证，暂不可使用共享功能")
	ErrFileNotFound                   = errors.New("文件不存在")
	ErrFolderNameRequired             = errors.New("文件夹名称不能为空")
	ErrFolderNameTooLong              = errors.New("文件夹名称不能超过 255 个字符")
	ErrFolderDescriptionTooLong       = errors.New("文件夹描述不能超过 4096 个字符")
	ErrWorkspaceStorageQuotaExceeded  = errors.New("已达到工作区存储空间上限")
	ErrReservedFolderName             = errors.New("不能使用系统保留的文件夹名称")
	ErrParentFolderNotFound           = errors.New("父文件夹不存在")
	ErrDuplicateFolderName            = errors.New("同名文件夹已存在")
	ErrUnsupportedDocumentType        = errors.New("不支持的文档类型")
	ErrUnsupportedImageTarget         = errors.New("不支持的图片上传目标")
	ErrDocumentTitleRequired          = errors.New("文档标题不能为空")
	ErrDocumentTitleTooLong           = errors.New("文档标题不能超过 255 个字符")
	ErrDocumentExcerptTooLong         = errors.New("文档介绍不能超过 500 个字符")
	ErrPublicDocumentNotFound         = errors.New("公开文档不存在")
	ErrPublicAccessInvalid            = errors.New("无效的公开访问级别")
	ErrPublicDocumentAuthRequired     = errors.New("需要登录后查看该文档")
	ErrFolderNotFound                 = errors.New("文件夹不存在")
	ErrDuplicateDocumentTitle         = errors.New("同名文档已存在")
	ErrImageTargetNotFound            = errors.New("图片上传目标不存在")
	ErrTargetFolderNotFoundOrDeleted  = errors.New("目标文件夹不存在或已被删除")
	ErrFolderNotFoundOrDeleted        = errors.New("文件夹不存在或已被删除")
	ErrTargetParentNotFoundOrDeleted  = errors.New("目标父文件夹不存在或已被删除")
	ErrFolderMoveCycle                = errors.New("不能将文件夹移动到其子文件夹下")
)
